### PR TITLE
Various tweaks

### PR DESCRIPTION
**Pull request by rcombs**

### CODE REVIEW

**Comment by youknowone** [comment]
Thanks for fixing lots of glitches.

I have a question for the openssl one. To "statically link against OpenSSL from Homebrew", is there more steps to build the project? Or is it just ok without special processing?

**Comment by rcombs** [comment]
It just requires you to have run `brew install openssl`. There are a number of other ways you could pull in OpenSSL (as a submodule, for instance), but this was the easiest for me.

Please hold off on merging commits past the OpenSSL one for a bit; I have a couple related tweaks to push and am addressing a couple crashes in text handling.

**Comment by youknowone** [comment]
I tried to build this version and getting error:
```
error: /usr/local/etc/openssl/certs/osx_cert.pem: No such file or directory
```

Any idea why no osx_cert.pem for me?

**Comment by youknowone** [comment]
Any help for `osx_cert.pem`? I think your patch have lots of nice fix fure problems. But without solving `osx_cert.pem`, I think I should do partial merge without the ssl one.

I don't get the file even after instealling openssl with homebrew

**Comment by rcombs** [comment]
That should be fixed now (the name changed to `cert.pem`).

**Comment by youknowone** [comment]
I will merge this PR today. Sorry for late. I just forgot about it without a specific reason.

Questions:
- Does `ad10600` fix this issue?  https://github.com/xchataqua/xchataqua/issues/227
- Do you want to keep going to develop xchat aqua? I can add you as a collaborator. Actually, you did a lot much more than me in 2016.

**Comment by youknowone** [comment]
Pre-released: https://github.com/xchataqua/xchataqua/releases/tag/appstore-1.18.0

**Comment by youknowone** [comment]
I found openssl libs are not statically linked in the correct way. otool shows the binary still is pointing dylibs and it is required dynamically.

**Pull request merged**
